name: iOS CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Xcode
      run: sudo xcode-select -s /Applications/Xcode_15.0.app

    - name: List available simulators  # Log available simulators to verify
      run: xcrun simctl list

    - name: Build and test
      run: |
        xcodebuild clean test \
          -scheme FoodMenu \
          -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest' \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
      working-directory: ./FoodMenu  # Adjust the directory path if necessary

    - name: Show logs in case of failure
      if: failure()
      run: |
        cat ~/Library/Logs/DiagnosticReports/xcodebuild*.crash
        tail -n 2000 ~/Library/Logs/xcbuild/*.log
