name: iOS CI

on:
  push:
    branches:
      - main  # Run tests on push to the main branch
  pull_request:
    branches:
      - main  # Run tests on pull requests to the main branch

jobs:
  test:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Xcode
      run: sudo xcode-select -s /Applications/Xcode_15.0.app  # Ensure you're using the right version

    - name: Build and test
      run: xcodebuild test -workspace YourProjectName.xcworkspace -scheme YourProjectName -destination 'platform=iOS Simulator,name=iPhone 14'
