name: iOS CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Xcode
      run: sudo xcode-select -s /Applications/Xcode_15.0.app

    - name: List available simulators
      run: xcrun simctl list

    - name: List root directory contents
      run: ls -la
      working-directory: .

    - name: List FoodMenu directory contents
      run: ls -la FoodMenu
      working-directory: .

    - name: Build and test
      run: |
        set -o pipefail
        xcodebuild clean test \
          -project FoodMenu.xcodeproj \
          -scheme FoodMenu \
          -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest' \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | tee xcodebuild.log
      working-directory: .

    - name: Show logs in case of failure
      if: failure()
      run: |
        cat xcodebuild.log
        cat ~/Library/Logs/DiagnosticReports/xcodebuild*.crash
        tail -n 2000 ~/Library/Logs/xcbuild/*.log